"""add_done_to_task

Revision ID: 17e1b67b9144
Revises: 908498b4a705
Create Date: 2024-04-25 16:13:11.867137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17e1b67b9144'
down_revision: Union[str, None] = '908498b4a705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_tasks', sa.Column('done_at', sa.DateTime(), nullable=True))
    op.add_column('request_tasks', sa.Column('is_done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_tasks', 'is_done')
    op.drop_column('request_tasks', 'done_at')
    # ### end Alembic commands ###
