"""add_ending_at

Revision ID: 74a20bf3cadc
Revises: 17e1b67b9144
Create Date: 2024-04-26 10:08:00.150182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74a20bf3cadc'
down_revision: Union[str, None] = '17e1b67b9144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_tasks', sa.Column('ending_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_tasks', 'ending_at')
    # ### end Alembic commands ###
