"""loaddata

Revision ID: eb8b4e46b6a0
Revises: f9c6c066dab3
Create Date: 2024-04-27 19:33:16.038781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from load_data import load_data_from_json

# revision identifiers, used by Alembic.
revision: str = 'eb8b4e46b6a0'
down_revision: Union[str, None] = 'f9c6c066dab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    load_data_from_json("data.json")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
