"""loaddata

Revision ID: eb8b4e46b6a0
Revises: f9c6c066dab3
Create Date: 2024-04-27 19:33:16.038781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb8b4e46b6a0'
down_revision: Union[str, None] = 'f9c6c066dab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

priority_table = sa.sql.table('priorities',
                              sa.Column('id', sa.Integer),
                              sa.Column('name', sa.String))

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(priority_table, [
      {
         "id":1,
         "name":"lowest"
      },
      {
         "id":2,
         "name":"low"
      },
      {
         "id":3,
         "name":"medium"
      },
      {
         "id":4,
         "name":"high"
      },
      {
         "id":5,
         "name":"highest"
      }
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM priorities")
    # ### end Alembic commands ###
