"""Add RequestTask.location_lng_lat column

Revision ID: f9c6c066dab3
Revises: 3ebcbefe342a
Create Date: 2024-04-27 16:30:20.476108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c6c066dab3'
down_revision: Union[str, None] = '3ebcbefe342a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_tasks', sa.Column('location_lng_lat', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_tasks', 'location_lng_lat')
    # ### end Alembic commands ###
